### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by JoseCage** [doesangueorg/doesangue-core#23]
Criar uma landing page para apresentação do projeto para visitantes, patrocinadores.

#### Itens a se destacar no desenvolvimento da página:

- [ ]  Menu de navegação (navbar)

- [ ] Carrosel com imagens descritivas sobre o projeto.

- [ ] Área com informações sobre como funciona a rede

- [ ] Área com **call_for_action** para registar na plataforma

- [ ] Área para exibição de Testemunhos de usuários e instituições

**Comment by doriel** [comment]
@JoseCage Logo para a Landing...

**Comment by JoseCage** [comment]
@doriel Ainda não tenho o logo criado.. Fora que não sei fazer logo :smile:

**Comment by JoseCage** [comment]
@doriel fiz um rabisco nada a ver aqui. Creio que vou tentar falar com alguém para fazer o logotipo. Mas se possivel fazermos a landing page antes disso :smile: :smile_cat:

**Comment by JoseCage** [comment]
Fiz um rabisco "wireframe" sobre a ideia básica do que pode ter na landingpage.
Sei que está muito fora do normal mas talvez dê para basear..

![1-home](https://user-images.githubusercontent.com/4200487/29528672-c023b13e-8694-11e7-84f7-c0a5c45da37a.png)

**Comment by doriel** [comment]
@JoseCage já tens um Repo para a "Landing" essa issue não deveria estar lá?

**Comment by doriel** [comment]
@JoseCage  podes fazer setup com bootstrap e Sass(No Repo da landing)?

**Comment by JoseCage** [comment]
Vou fazer o setup..

O repo é https://github.com/doesangueorg/doesangueorg.github.io

**Comment by doriel** [comment]
@JoseCage ok

**Comment by JoseCage** [comment]
Quanto as issues. Também pensei nesta opção..

Mas na altura não tinha a ideia de separar tudo em repos por isso acabou ficando a bagunça aqui..
